// <auto-generated />
using System;
using ImmichFrame.WebApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImmichFrame.WebApi.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("ImmichFrame.WebApi.Persistence.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Albums")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludedAlbums")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImagesFromDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImagesFromDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImagesUntilDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImmichServerUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("People")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowFavorites")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMemories")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowVideos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("ImmichFrame.WebApi.Persistence.Entities.GeneralSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthenticationSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseFontSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClockDateFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClockFormat")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DownloadImages")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImageFill")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageLocationFormat")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImagePan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImageZoom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoDateFormat")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlayAudio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("TEXT");

                    b.Property<int>("RefreshAlbumPeopleInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RenewImagesDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryColor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowAlbumName")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowClock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowImageDesc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowImageLocation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPeopleDesc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPhotoDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowProgressBar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTagsDesc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowWeatherDescription")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TransitionDuration")
                        .HasColumnType("REAL");

                    b.Property<string>("UnitSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherIconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherLatLong")
                        .HasColumnType("TEXT");

                    b.Property<string>("Webcalendars")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Webhook")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
